version: "3.8"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - my-data:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "80:80"
        environment:
            DB_DATABASE: dbname
            DB_USERNAME: root
            DB_PASSWORD: test
            DB_HOST: db
        volumes:
            - ./leafsapi-project:/var/www/html
        links:
            - db
        networks:
            - default
volumes:
    my-data:
